### ISSUE TITLE
[Question]: 为什么Insert.java中execute时既不用对rowkey进行排序，也无需向执行插入的函数传入rowkeyName？

### ISSUE THREAD

**Issue by ww3113306** [oceanbase/obkv-table-client-java#136]
### Description

为什么Insert.java中execute时既不用对rowkey进行排序，也无需向执行插入的函数传入rowkeyName？
这样如果用户指定主键顺序时，如果顺序和建表时不一样，不会导致出错吗？

**Comment by IHEII** [comment]
[insert](https://github.com/oceanbase/obkv-table-client-java/wiki/%E5%8D%95%E8%A1%8C%E6%93%8D%E4%BD%9C%E6%8E%A5%E5%8F%A3#1-insert) will store the rowkey name information, and compare to the meta info from observer to find out the correct tablet.
But you should set the rowkey in the same order as the order of how you create your table now since the client does not know the order of the rowkey now.
